name: Checkout and patch source
description: Checkout a Git repository and auto-apply patches from patches/<repository>/

inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true
  ref:
    description: >
      The branch, tag or SHA to checkout. When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. Otherwise, uses the default branch.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        clean: false

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.repository }}
        fetch-depth: 0

    - shell: bash
      if: hashFiles(format('patches/{0}/*.patch', inputs.repository)) != ''
      run: git -C "${{ inputs.repository }}" apply --verbose "${{ github.workspace }}"/patches/${{ inputs.repository }}/*
