name: tox

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      ref:
        type: string
        required: true

jobs:
  tox:
    name: ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - pep8
          - py3
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - run: uv tool install bindep
      - run: sudo apt-get update
      - run: |
          if [ -f bindep.txt ] || [ -f other-requirements.txt ]; then
            packages="$(bindep -b test "${{ matrix.env }}" || true)"
            if [ -n "$packages" ]; then
              sudo apt-get install -y $packages
            fi
            bindep -b test "${{ matrix.env }}"
          fi
        working-directory: ${{ inputs.repository }}
      - run: uv tool install tox --with tox-uv
      - run: tox --runner virtualenv -e ${{ matrix.env }}
        working-directory: ${{ inputs.repository }}
