name: tox

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      ref:
        type: string
        required: true

jobs:
  tox:
    name: ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - pep8
          - py3
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: step-security/setup-uv@479ad0a90c4286eda3535eb7db396ed723b63fb7 # v8.1.0
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@ee412cafe33e0d7d8b3bc7d0ca64c9f155e293c7 # main
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
      - run: uv tool install bindep
      - run: sudo apt-get update
      - run: |
          if [ -f bindep.txt ] || [ -f other-requirements.txt ]; then
            packages="$(bindep -b test "${{ matrix.env }}" || true)"
            if [ -n "$packages" ]; then
              sudo apt-get install -y $packages
            fi
            bindep -b test "${{ matrix.env }}"
          fi
        working-directory: ${{ inputs.repository }}
      - run: uv tool install tox --with tox-uv
      - run: tox --runner virtualenv -e ${{ matrix.env }}
        working-directory: ${{ inputs.repository }}
